[common]
server_addr = 82.157.174.100
server_port = 7000
token = 60d8a83c544e6168db

# 1️⃣ SSH（远程开发核心）
[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000

# 2️⃣ 远程桌面（可选）
#[rdp]
#type = tcp
#local_port = 3389
#remote_port = 6001

[vnc]
type = tcp
local_ip = 127.0.0.1
local_port = 5901
remote_port = 6001

